'use strict';
const $ = (s, root=document) => root.querySelector(s);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL = value => {try {const u=new URL(value); return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}};
const state = {user:null, photos:[], offset:0, more:true, filter:'All', search:'', mine:false, generation:0};
let refreshPromise=null, toastTimer, previewURL;
const token = () => sessionStorage.getItem('photoshare.access');
function saveTokens(data){sessionStorage.setItem('photoshare.access',data.access_token);sessionStorage.setItem('photoshare.refresh',data.refresh_token);}
function signout(){sessionStorage.removeItem('photoshare.access');sessionStorage.removeItem('photoshare.refresh');state.user=null;header();location.hash='signin';}
async function api(path,options={},retry=true){
 const headers=new Headers(options.headers||{}); if(token())headers.set('Authorization','Bearer '+token());
 if(options.json!==undefined){headers.set('Content-Type','application/json');options={...options,body:JSON.stringify(options.json)};}
 let response;try{response=await fetch('/api'+path,{...options,headers});}catch{throw Error('Cannot reach the server. Check that FastAPI is running.');}
 if(response.status===401 && retry && !path.startsWith('/auth/') && sessionStorage.getItem('photoshare.refresh')){
  if(!refreshPromise)refreshPromise=fetch('/api/auth/refresh_token',{headers:{Authorization:'Bearer '+sessionStorage.getItem('photoshare.refresh')}}).then(async r=>{if(!r.ok)throw Error('Your session expired. Please sign in again.');saveTokens(await r.json());}).finally(()=>refreshPromise=null);
  try{await refreshPromise;return await api(path,options,false);}catch(error){signout();throw error;}
 }
 if(response.status===204)return null;
 const data=await response.json().catch(()=>null);
 if(!response.ok){const detail=data?.detail;throw Error(Array.isArray(detail)?detail.map(d=>`${d.loc?.slice(-1)[0]||'Field'}: ${d.msg}`).join('; '):typeof detail==='string'?detail:response.status===429?'Too many requests. Please wait 20 seconds and try again.':`Request failed (${response.status}). Please try again.`);}
 return data;
}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').style.display='block';toastTimer=setTimeout(()=>$('#toast').style.display='none',4500);}
function errorBox(form,error){let box=$('.error',form);if(!box){box=document.createElement('div');box.className='error';box.setAttribute('role','alert');form.prepend(box);}box.textContent=error.message;}
function bindForm(form,handler){form.addEventListener('submit',async event=>{event.preventDefault();const button=$('[type=submit]',form);if(button?.disabled)return;$('.error',form)?.remove();if(button)button.disabled=true;try{await handler(new FormData(form));}catch(error){errorBox(form,error);}finally{if(button)button.disabled=false;}});}
function avatarContent(user) {
 const initial = esc(user.username?.[0]?.toUpperCase() || 'U');
 const url = safeURL(user.avatar);
 return `<span>${initial}</span>${url ? `<img class="avatar-image" src="${esc(url)}" alt="${esc(user.username || 'User')} avatar">` : ''}`;
}
function bindAvatarFallbacks(root) {
 root.querySelectorAll('.avatar-image').forEach(image => {
  image.addEventListener('error', () => image.remove(), {once: true});
  if (image.complete && !image.naturalWidth) image.remove();
 });
}
function header(){const u=state.user;$('#account').innerHTML=u?`<a class="avatar" href="#profile" aria-label="Your profile">${avatarContent(u)}</a><a href="#profile" class="account-name">${esc(u.username)}<span class="role">${esc(u.role)}</span></a><button class="text-button" id="signout">Sign out</button>`:'<a class="secondary" href="#signin">Sign in</a>';$('#signout')?.addEventListener('click',signout);$('#admin-nav').hidden=u?.role!=='admin';bindAvatarFallbacks($('#account'));}
function needUser(){if(state.user)return true;location.hash='signin';return false;}
const tagsHTML = tags => (tags||[]).map(t=>`<span class="tag">${esc(typeof t==='string'?t:t.name)}</span>`).join('');
function tagEditor(root,initial=[]){let tags=[...initial];root.innerHTML='<div class="tags"></div><input aria-label="Add a tag" placeholder="Add a tag and press Enter"><span class="hint"></span>';function draw(){$('.tags',root).innerHTML=tags.map((t,i)=>`<span class="tag">${esc(t)} <button type="button" data-remove="${i}" aria-label="Remove ${esc(t)}">×</button></span>`).join('');$('.hint',root).textContent=`${tags.length} / 5 tags`;root.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{tags.splice(Number(b.dataset.remove),1);draw();});}function add(){const input=$('input',root);const next=input.value.split(',').map(t=>t.trim().toLowerCase()).filter(Boolean);if(next.some(t=>t.length>50))throw Error('Each tag must be at most 50 characters.');const unique=[...new Set([...tags,...next])];if(unique.length>5)throw Error('You can add up to 5 tags.');tags=unique;input.value='';draw();} $('input',root).onkeydown=e=>{if(e.key==='Enter'||e.key===','){e.preventDefault();try{add();}catch(err){toast(err.message);}}};draw();return ()=>{add();return tags;};}
async function gallery(mine){if(mine&&!needUser())return;state.mine=mine;state.offset=0;state.photos=[];state.filter='All';state.search='';$('#main').innerHTML=`<div class="heading"><div><div class="eyebrow">A world of little moments</div><h1>${mine?'My photos':'Explore photos'}</h1><p class="subtitle">${mine?'Your memories, all in one place.':'Find a little inspiration. Share a little of your world.'}</p></div><a href="#upload" class="button">＋ Upload photo</a></div><div class="toolbar"><span aria-hidden="true">⌕</span><input id="search" type="search" aria-label="Search photos and tags" placeholder="Search descriptions, tags…"><span class="muted" id="count"></span></div><div class="filters" id="filters"></div><div id="gallery-content" class="loading"><span class="spinner"></span></div><div class="load-more"><button class="secondary" id="more">Load more photos</button></div>`;$('#search').oninput=e=>{state.search=e.target.value.toLowerCase();drawGallery();};$('#more').onclick=loadPhotos;await loadPhotos();}
async function loadPhotos(){const generation=state.generation;const more=$('#more');if(!more)return;more.disabled=true;try{const rows=await api(`/photos?limit=100&offset=${state.offset}`);if(generation!==state.generation)return;state.photos.push(...rows);state.offset+=rows.length;state.more=rows.length===100;drawGallery();}catch(error){if(generation!==state.generation)return;$('#gallery-content').className='error';$('#gallery-content').textContent=error.message;}finally{if(generation===state.generation){more.disabled=false;more.hidden=!state.more;}}}
function drawGallery(){const root=$('#gallery-content');if(!root)return;const available=state.photos.filter(p=>!state.mine||p.user_id===state.user?.id);let names=['All',...new Set(available.flatMap(p=>p.tags.map(t=>t.name)))].slice(0,14);$('#filters').innerHTML=names.map(n=>`<button class="filter ${n===state.filter?'active':''}" data-filter="${esc(n)}">${esc(n)}</button>`).join('');$('#filters').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;drawGallery();});const rows=available.filter(p=>(state.filter==='All'||p.tags.some(t=>t.name===state.filter))&&`${p.description||''} ${p.tags.map(t=>t.name).join(' ')}`.toLowerCase().includes(state.search));$('#count').textContent=`${rows.length} photos`;root.className=rows.length?'grid':'';root.innerHTML=rows.length?rows.map(p=>`<article class="card"><button class="photo-open" data-photo="${p.id}" aria-label="View photo ${p.id}"><img src="${esc(safeURL(p.url))}" alt="${esc(p.description||'Photo '+p.id)}" loading="lazy"></button><div class="card-body"><p class="card-title">${esc(p.description||'Untitled moment')}</p><div class="tags">${tagsHTML(p.tags)}</div><div class="card-bottom"><span>PHOTO ${String(p.id).padStart(3,'0')}</span><button data-photo="${p.id}">View & comment ↗</button></div></div></article>`).join(''):$('#empty').innerHTML;root.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>location.hash='photo/'+b.dataset.photo);}
function auth(mode='signin'){const signup=mode==='signup';$('#main').innerHTML=`<div class="auth-layout"><div class="auth-art"><span class="brand" style="color:white">▧ PhotoShare</span><div><h2>Every photo.<br>A little story.</h2><p>A place for the moments you want to hold on to — and share with the world.</p></div><span class="hint" style="color:#fff;z-index:1">Capture. Connect. Be inspired.</span></div><div class="auth-form"><span class="eyebrow">Welcome ${signup?'aboard':'back'}</span><h1>${signup?'Create your account':'Sign in to PhotoShare'}</h1><p class="subtitle">${signup?'Your next chapter starts with a photo.':'Your photos and favorite moments are waiting.'}</p><form id="auth-form">${signup?'<label class="field">Username<input name="username" required minlength="3" maxlength="50" autocomplete="username"></label>':''}<label class="field">Email<input name="email" type="email" required autocomplete="email" placeholder="you@example.com"></label><label class="field">Password<input name="password" type="password" required ${signup?'minlength="6" maxlength="8"':''} autocomplete="${signup?'new-password':'current-password'}">${signup?'<span class="hint">6–8 characters, as required by this API.</span>':''}</label><button class="primary wide" type="submit">${signup?'Create account':'Sign in'}</button></form><div class="auth-links">${signup?'Already have an account?':'New to PhotoShare?'} <a href="#${signup?'signin':'signup'}">${signup?'Sign in':'Sign up'}</a></div><div class="auth-links"><a href="#verify">Confirm email</a> · <a href="#reset">Forgot password?</a></div></div></div>`;bindForm($('#auth-form'),async data=>{if(signup){await api('/auth/signup',{method:'POST',json:Object.fromEntries(data)});location.hash='verify';toast('Account created. Check your email to confirm it.');}else{const body=new URLSearchParams({username:data.get('email'),password:data.get('password')});const tokens=await api('/auth/login',{method:'POST',body});saveTokens(tokens);state.user=await api('/users/me');header();location.hash='photos';}});}
function emailFlow(reset){$('#main').innerHTML=`<section class="panel profile"><div class="eyebrow">Account access</div><h1>${reset?'Reset password':'Confirm your email'}</h1><p class="subtitle">Request an email, then paste the token from its link below.</p><form id="email-form"><label class="field">Email<input name="email" type="email" required></label><button class="primary" type="submit">Send ${reset?'reset':'confirmation'} email</button></form><hr style="border:0;border-top:1px solid var(--line);margin:28px 0"><form id="token-form"><label class="field">Token<input name="token" required autocomplete="off"></label>${reset?'<label class="field">New password<input name="password" type="password" minlength="6" maxlength="8" required autocomplete="new-password"></label>':''}<button class="primary" type="submit">${reset?'Save new password':'Confirm email'}</button></form><p><a href="#signin">Back to sign in</a></p></section>`;bindForm($('#email-form'),async data=>{await api(reset?'/auth/request_password_reset':'/auth/request_email',{method:'POST',json:Object.fromEntries(data)});toast('Check your email for the next step.');});bindForm($('#token-form'),async data=>{await api(reset?'/auth/reset_password':'/auth/confirmed_email/'+encodeURIComponent(data.get('token')),reset?{method:'POST',json:Object.fromEntries(data)}:{});toast(reset?'Password changed. Please sign in.':'Email confirmed. You can sign in.');location.hash='signin';});}
function upload(){if(!needUser())return;$('#main').innerHTML=`<a class="back" href="#photos">← Back to photos</a><div class="heading"><div><h1>Share a new moment</h1><p class="subtitle">A photo, a few words, a little piece of your world.</p></div></div><form class="panel upload-layout" id="upload-form"><label class="drop" id="drop"><input name="file" type="file" accept="image/*" required><div id="preview"><span class="symbol">▧</span><h3>Drag and drop your photo</h3><p class="muted">or click to browse files</p><span class="hint">Choose an image from your device</span></div></label><div><label class="field">Description<textarea name="description" maxlength="250" required placeholder="Tell the story behind this photo…"></textarea><span class="hint">Up to 250 characters</span></label><div class="field">Tags <span class="muted">(optional)</span><div id="upload-tags" class="tag-editor"></div></div><div class="actions"><a href="#photos" class="secondary">Cancel</a><button class="primary" type="submit">Upload photo ↗</button></div></div></form>`;const getTags=tagEditor($('#upload-tags'));const input=$('[name=file]');const preview=()=>{const file=input.files[0];if(!file)return;if(previewURL)URL.revokeObjectURL(previewURL);previewURL=URL.createObjectURL(file);$('#preview').innerHTML=`<img src="${previewURL}" alt="Selected photo preview"><p class="muted">${esc(file.name)}</p>`;};input.onchange=preview;const drop=$('#drop');['dragenter','dragover'].forEach(e=>drop.addEventListener(e,event=>{event.preventDefault();drop.classList.add('dragging');}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,event=>{event.preventDefault();drop.classList.remove('dragging');}));drop.addEventListener('drop',e=>{if(e.dataTransfer.files.length){input.files=e.dataTransfer.files;preview();}});bindForm($('#upload-form'),async data=>{if(!input.files[0]?.type.startsWith('image/'))throw Error('Please choose an image.');const description=data.get('description').trim();if(!description)throw Error('Please add a description.');data.set('description',description);getTags().forEach(t=>data.append('tags',t));const photo=await api('/photos/upload',{method:'POST',body:data});state.photos.push(photo);toast('Your photo is ready to share.');location.hash='photo/'+photo.id;});}
function modal(title,html){$('#modal-content').innerHTML=`<div class="modal-heading"><h2>${esc(title)}</h2><button class="close" aria-label="Close dialog">×</button></div>${html}`;$('.close',$('#modal')).onclick=()=>$('#modal').close();if(!$('#modal').open)$('#modal').showModal();}
function canManage(photo){return state.user&&(state.user.role==='admin'||state.user.id===photo.user_id);}
async function findPhoto(id){let photo=state.photos.find(p=>p.id===id);if(photo)return photo;for(let offset=0;;offset+=100){const rows=await api(`/photos?limit=100&offset=${offset}`);photo=rows.find(p=>p.id===id);if(photo){state.photos.push(photo);return photo;}if(rows.length<100)throw Error('Photo not found.');}}
async function detail(id){const generation=state.generation;const photo=await findPhoto(id);if(generation!==state.generation)return;$('#main').innerHTML=`<a class="back" href="#photos">← Back to photos</a><section class="panel"><div class="detail"><img class="detail-image" src="${esc(safeURL(photo.url))}" alt="${esc(photo.description||'Photo')}"/><div><div class="eyebrow">Photo ${String(id).padStart(3,'0')}</div><h1>A moment worth sharing</h1><p class="muted">${photo.user_id===state.user?.id?'Your photo':'Shared with the community'}</p><p class="description">${esc(photo.description||'No description yet.')}</p><div class="tags">${tagsHTML(photo.tags)}</div><div class="actions"><a class="secondary" target="_blank" rel="noopener noreferrer" href="${esc(safeURL(photo.url))}">Open original ↗</a>${canManage(photo)?'<button id="transform" class="primary">Create transform link</button><button id="edit" class="secondary">Edit photo</button><button id="delete" class="secondary danger">Delete</button>':''}</div></div></div><section class="comments"><h2>Conversation <span id="comment-count" class="muted"></span></h2><div id="comment-list" class="muted">Loading comments…</div>${state.user?'<form id="comment-form" class="comment-form"><textarea name="text" aria-label="Write a comment" placeholder="Leave a little kindness…" minlength="2" maxlength="255" required></textarea><button class="primary" type="submit">Post</button></form>':'<p class="muted"><a href="#signin">Sign in</a> to read and leave comments.</p>'}</section></section>`;$('#transform')?.addEventListener('click',()=>transformModal(photo));$('#edit')?.addEventListener('click',()=>editModal(photo));$('#delete')?.addEventListener('click',()=>{modal('Delete this photo?',`<p>This removes the photo from your gallery. This action cannot be undone.</p><form id="delete-form"><div class="actions"><button type="button" class="secondary" id="cancel-delete">Cancel</button><button type="submit" class="secondary danger">Delete photo</button></div></form>`);$('#cancel-delete').onclick=()=>$('#modal').close();bindForm($('#delete-form'),async()=>{await api('/photos/'+id,{method:'DELETE'});state.photos=state.photos.filter(p=>p.id!==id);$('#modal').close();location.hash='photos';toast('Photo deleted.');});});if(state.user){bindForm($('#comment-form'),async data=>{await api(`/comments/photos/${id}/comments`,{method:'POST',json:{text:data.get('text').trim()}});$('#comment-form').reset();await loadComments(id);});await loadComments(id);}else $('#comment-list').textContent='';}
async function loadComments(id){const generation=state.generation;try{const rows=await api(`/comments/photos/${id}/comments`);if(generation!==state.generation)return;$('#comment-count').textContent=`(${rows.length})`;$('#comment-list').innerHTML=rows.length?rows.map(c=>`<article class="comment"><span class="avatar">${c.user_id===state.user.id?'Y':'U'}</span><div class="comment-body"><strong style="font-size:12px">${c.user_id===state.user.id?'You':c.user_id?'User #'+c.user_id:'Community member'}</strong><p>${esc(c.text)}</p><div class="comment-meta"><time>${esc(new Date(c.created_at).toLocaleString())}</time>${c.updated_at!==c.created_at?'<span>Edited</span>':''}${c.user_id===state.user.id?`<button class="text-button" data-edit-comment="${c.id}">Edit</button>`:''}${['admin','moderator'].includes(state.user.role)?`<button class="text-button" data-delete-comment="${c.id}">Delete</button>`:''}</div></div></article>`).join(''):'<p class="muted">No comments yet. Start the conversation.</p>';document.querySelectorAll('[data-edit-comment]').forEach(b=>b.onclick=()=>{const c=rows.find(x=>x.id===Number(b.dataset.editComment));modal('Edit your comment',`<form id="comment-edit"><label class="field">Comment<textarea name="text" minlength="2" maxlength="255" required>${esc(c.text)}</textarea></label><button type="submit" class="primary">Save changes</button></form>`);bindForm($('#comment-edit'),async data=>{await api('/comments/comments/'+c.id,{method:'PUT',json:{text:data.get('text').trim()}});$('#modal').close();await loadComments(id);});});document.querySelectorAll('[data-delete-comment]').forEach(b=>b.onclick=async()=>{if(!confirm('Delete this comment?'))return;try{await api('/comments/comments/'+b.dataset.deleteComment,{method:'DELETE'});await loadComments(id);}catch(e){toast(e.message);}});}catch(e){if(generation===state.generation)$('#comment-list').textContent=e.message;}}
function editModal(photo){modal('Edit photo',`<form id="edit-form"><div class="modal-grid"><img class="modal-photo" src="${esc(safeURL(photo.url))}" alt="Photo preview"><div><label class="field">Description<textarea name="description" maxlength="250">${esc(photo.description)}</textarea></label><label class="field">Tags (up to 5)</label><div id="edit-tags" class="tag-editor"></div></div></div><div class="actions"><button class="primary" type="submit">Save changes</button></div></form>`);const getTags=tagEditor($('#edit-tags'),photo.tags.map(t=>t.name));bindForm($('#edit-form'),async data=>{const tags=getTags();const description=data.get('description');await api('/photos/'+photo.id,{method:'PUT',json:{description,tags}});photo.description=description;photo.tags=tags.map(name=>({name}));$('#modal').close();await detail(photo.id);toast('Changes saved.');});}
function transformModal(photo){modal('Create transformed image link',`<form id="transform-form"><div class="modal-grid"><img class="modal-photo" src="${esc(safeURL(photo.url))}" alt="Original photo"><div><label class="field">Transformation<select name="transformation"><option value="resize">Resize · up to 800 × 800</option><option value="avatar">Round avatar · 200 × 200</option><option value="grayscale">Black & white</option></select></label><p class="muted">Create a new perspective. Your original photo stays just as it is.</p><label class="check"><input type="checkbox" name="qr" checked> Generate QR code</label></div></div><div class="actions"><button class="primary" type="submit">Create link ↗</button></div></form>`);bindForm($('#transform-form'),async data=>{const record=await api(`/photos/transform?photo_id=${photo.id}&transformation=${data.get('transformation')}`,{method:'POST'});showResult(record);if(data.has('qr'))await generateQR(record);});}
function showResult(record){modal('Your image is ready to share',`<div class="modal-grid"><img class="modal-photo" src="${esc(safeURL(record.image_url))}" alt="Transformed photo"><div><label class="field">Public image link</label><div class="url-row"><input id="share-url" readonly aria-label="Public image link" value="${esc(safeURL(record.image_url))}"><button class="secondary" id="copy">Copy</button></div><p><a href="${esc(safeURL(record.image_url))}" target="_blank" rel="noopener noreferrer">Open image ↗</a></p><div id="qr-result"></div><button id="generate-qr" class="secondary">Generate QR code</button><p class="hint">Anyone with this link can view the photo.</p></div></div>`);$('#copy').onclick=async()=>{try{await navigator.clipboard.writeText(record.image_url);toast('Link copied.');}catch{$('#share-url').select();toast('Select and copy the link.');}};$('#generate-qr').onclick=()=>generateQR(record);}
async function generateQR(record){const button=$('#generate-qr');if(!button)return;button.disabled=true;button.textContent='Generating QR…';try{const result=await api('/photos/qrcode?transformation_id='+record.id,{method:'POST'});if(!$('#qr-result'))return;$('#qr-result').innerHTML=`<img class="qr" src="${esc(safeURL(result.qr_code_url))}" alt="QR code for the transformed photo"><p><a target="_blank" rel="noopener noreferrer" href="${esc(safeURL(result.qr_code_url))}">Open / save QR code ↗</a></p>`;button.hidden=true;}catch(e){toast(e.message);button.textContent='Retry QR generation';}finally{button.disabled=false;}}
function admin(){if(!needUser())return;if(state.user.role!=='admin'){ $('#main').innerHTML='<div class="empty"><h1>Administrator access required</h1><p>This page is available to administrators only.</p></div>';return;}$('#main').innerHTML=`<div class="heading"><div><div class="eyebrow">Administration</div><h1>Manage access</h1><p class="subtitle">Give people the right role in your community.</p></div></div><section class="panel profile"><h2>Change a user’s role</h2><form id="role-form"><label class="field">User email<input type="email" name="email" placeholder="user@example.com" required></label><label class="field">Role<select name="role"><option value="user">User</option><option value="moderator">Moderator</option><option value="admin">Administrator</option></select></label><p class="hint">Moderators can remove comments. Administrators can manage photos and assign roles.</p><button class="primary" type="submit">Save role</button></form><div id="role-result"></div></section>`;bindForm($('#role-form'),async data=>{const result=await api('/users/role',{method:'PATCH',json:Object.fromEntries(data)});$('#role-result').innerHTML=`<p class="success">${esc(result.email)} now has the ${esc(result.role)} role.</p>`;if(result.id===state.user.id){state.user.role=result.role;header();if(result.role!=='admin')location.hash='profile';}});}
function profile(){if(!needUser())return;$('#main').innerHTML=`<section class="panel profile"><div class="avatar profile-avatar" id="profile-avatar">${avatarContent(state.user)}</div><div class="eyebrow">Your account</div><h1>${esc(state.user.username)}</h1><div class="profile-line"><span>Email</span><strong>${esc(state.user.email)}</strong></div><div class="profile-line"><span>Role</span><strong>${esc(state.user.role)}</strong></div><form id="avatar-form" style="margin-top:25px"><label class="field">Profile picture<input type="file" name="file" accept="image/*" required></label><button type="submit" class="primary">Update avatar</button></form></section>`;bindAvatarFallbacks($('#main'));bindForm($('#avatar-form'),async data=>{const file=data.get('file');if(!file?.type.startsWith('image/'))throw Error('Please choose an image.');state.user=await api('/users/avatar',{method:'PATCH',body:data});header();$('#profile-avatar').innerHTML=avatarContent(state.user);bindAvatarFallbacks($('#profile-avatar'));$('#avatar-form').reset();toast('Avatar updated.');});}
async function route(){state.generation++;if(previewURL){URL.revokeObjectURL(previewURL);previewURL=null;}$('#modal').close();const path=location.hash.slice(1)||'photos';document.querySelectorAll('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===path));$('#main').innerHTML='<div class="loading"><span class="spinner"></span></div>';try{if(path==='photos'||path==='mine')await gallery(path==='mine');else if(path==='signin'||path==='signup')auth(path);else if(path==='verify'||path==='reset')emailFlow(path==='reset');else if(path==='upload')upload();else if(path==='admin')admin();else if(path==='profile')profile();else if(/^photo\/\d+$/.test(path))await detail(Number(path.split('/')[1]));else location.hash='photos';}catch(error){$('#main').innerHTML=`<div class="empty"><h2>We couldn’t load this page</h2><p>${esc(error.message)}</p><a href="#photos" class="button">Back to photos</a></div>`;}}
window.addEventListener('hashchange',route);
(async()=>{if(token()){try{state.user=await api('/users/me');}catch(error){toast(error.message);}}header();await route();})();
