"""Update create CRUD

Revision ID: 1e0db55dfa7d
Revises: a194de027bc1
Create Date: 2026-09-27 18:46:35.851209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0db55dfa7d'
down_revision: Union[str, Sequence[str], None] = 'a194de027bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_photos_user_id'), 'photos', ['user_id'], unique=False)
    op.create_foreign_key(None, 'photos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_index(op.f('ix_photos_user_id'), table_name='photos')
    op.drop_column('photos', 'user_id')
    # ### end Alembic commands ###
