"""create photo transformations

Revision ID: 247df1cd7323
Revises: 29e8d3b02a35
Create Date: 2026-09-25 19:06:22.550503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247df1cd7323'
down_revision: Union[str, Sequence[str], None] = '29e8d3b02a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_transformations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=False),
    sa.Column('transformation', sa.String(length=30), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('qr_code_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_transformations_photo_id'), 'photo_transformations', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_transformations_photo_id'), table_name='photo_transformations')
    op.drop_table('photo_transformations')
    # ### end Alembic commands ###
