"""add public_id to photos

Revision ID: 29e8d3b02a35
Revises: b2b10170fa79
Create Date: 2026-09-25 18:27:43.031393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e8d3b02a35'
down_revision: Union[str, Sequence[str], None] = 'b2b10170fa79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('public_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'public_id')
    # ### end Alembic commands ###
